// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telenec.Mail.Statistics.Server.Data;

#nullable disable

namespace Telenec.Mail.Statistics.Server.Migrations
{
    [DbContext(typeof(StatisticsDbContext))]
    partial class StatisticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Telenec.Mail.Statistics.Server.Models.Installation", b =>
                {
                    b.Property<string>("InstallationKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("InstallationKey");

                    b.HasIndex("CurrentVersion");

                    b.HasIndex("FirstSeenUtc");

                    b.HasIndex("LastSeenUtc");

                    b.ToTable("Installations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
