<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>

		<StartupObject>Telenec.Mail.Statistics.Admin.Program</StartupObject>

		<Version>0.1.0-test.1</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
		<PackageReference Include="Velopack" Version="1.2.0" />
	</ItemGroup>

</Project>